mysql_db {
  profile = "slick.jdbc.MySQLProfile$"
  db {
    driver = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://localhost:3306/evea_db?useSSL=false&serverTimezone=UTC"
    user = "root"
    password = "root"
    connectionPool = "HikariCP"
  }
}